---
- hosts: localhost
  connection: local
  vars:
    ssh_key: k8s
    k8s_version: v1.2.0
    k8s_num_nodes: 2
    k8s_security_group_name: k8s
    k8s_node_prefix: k8s
# This template name is specific to http://exoscale.ch, replace it
    k8s_template: Linux CoreOS stable 723 64-bit 10G Disk (2015-08-04-600521)
    k8s_instance_type: Tiny

  roles:
    - common
    - k8s
